export const CONSTANTS = {
  MIDI_CONNECTION_STATE_CONNECTED: 'connected',
  MIDI_CONNECTION_STATE_DISCONNECTED: 'disconnected',
  MIDI_CONNECTION_TYPE_INPUT: 'input',
  MIDI_CONNECTION_TYPE_OUTPUT: 'output',
  MIDI_STATUS_CONTROL_CHANGE: 0xB0,
  MIDI_WRITE_INTERVAL: 100
};
